# NumPy

numpy is python's package for doing math that is more advanced than +-*/

This includes special functions like cosine, exponential, sqrt, ...

On top of this we can use numpy to generate samples from many types of random variables

numpy also has a powerful data type to define vectors, matrices, and tensors

With these data types numpy also allows us to do linear algebra - matrix multiplication and matrix-vector solutions

In [1]:
# the first step of using numpy is to tell python to use it
import numpy as np

In [2]:
print(np.cos(np.pi))
print(np.sqrt(1.21))
print(np.log(np.exp(5.2)))

-1.0
1.1
5.2


In [3]:
# we can create numpy arrays by converting lists
# this is a vector
vec = np.array([1,2,3])
print(vec)
# we can create matrices by converting lists of lists
mat = np.array([[1,2,1],[4,5,9],[1,8,9]])
print('')
print(mat)
print('')
print(mat.T)

[1 2 3]

[[1 2 1]
 [4 5 9]
 [1 8 9]]

[[1 4 1]
 [2 5 8]
 [1 9 9]]


In [4]:
# there are lots of other ways to create numpy arrays
vec2 = np.arange(0,15)
print(vec2)
print('')
vec3 = np.arange(3,21,6)
print(vec3)


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]

[ 3  9 15]


In [5]:

vec4 = np.linspace(0,5,10)
print(vec4)
print('')
print(vec4.reshape(5,2))
vec4_reshaped = vec4.reshape(5,2)
print(vec4_reshaped)
print(vec4)

[0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]

[[0.         0.55555556]
 [1.11111111 1.66666667]
 [2.22222222 2.77777778]
 [3.33333333 3.88888889]
 [4.44444444 5.        ]]
[[0.         0.55555556]
 [1.11111111 1.66666667]
 [2.22222222 2.77777778]
 [3.33333333 3.88888889]
 [4.44444444 5.        ]]
[0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]


In [6]:
mat2 = np.zeros([5,3])
print(mat2)
mat3 = np.ones((3,5))
print('')
print(mat3)
mat4 = np.eye(5)
print('')
print(mat4)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [7]:
# we can +-*/ arrays together if they're the right size
vec5 = np.arange(1,6)
vec6 = np.arange(3,8)
print(vec5)
print(vec6)
print(vec5+vec6)
print(vec5*vec6)
print(1/vec5)
print(np.sqrt(vec6))

[1 2 3 4 5]
[3 4 5 6 7]
[ 4  6  8 10 12]
[ 3  8 15 24 35]
[1.         0.5        0.33333333 0.25       0.2       ]
[1.73205081 2.         2.23606798 2.44948974 2.64575131]


In [8]:
# we can do matrix multiplication
print(mat)
print('')
print(vec)
print()
product = np.matmul(mat,vec)
print(product)

[[1 2 1]
 [4 5 9]
 [1 8 9]]

[1 2 3]

[ 8 41 44]


In [9]:
print(np.linalg.solve(mat,product))
print('')
print(np.linalg.inv(mat))

[1. 2. 3.]

[[ 0.5         0.18518519 -0.24074074]
 [ 0.5        -0.14814815  0.09259259]
 [-0.5         0.11111111  0.05555556]]


In [10]:
# we can find the unique values in an array
vec7 = np.array(['blue','red','orange','purple','purple','orange','Red',6])
print(vec7)
print(np.unique(vec7))

['blue' 'red' 'orange' 'purple' 'purple' 'orange' 'Red' '6']
['6' 'Red' 'blue' 'orange' 'purple' 'red']


In [11]:
# we can also use numpy to generate samples of a random variable
rand_mat = np.random.rand(5,5) # uniform random variable
print(rand_mat)
rand_mat2 = np.random.randn(10,5) # standard normal random variable
print('')
print(rand_mat2)

[[0.80339305 0.3443665  0.11965859 0.33054602 0.82775485]
 [0.80834343 0.91693695 0.60062788 0.82067113 0.74608966]
 [0.2556618  0.8373035  0.30890033 0.59713354 0.42069145]
 [0.86890498 0.28781749 0.49102024 0.38748334 0.40055826]
 [0.62741964 0.001983   0.75107944 0.26270882 0.30729093]]

[[-1.18796881  1.60797976  0.19256138 -1.57018676  0.50343537]
 [-1.0667398   0.56265413 -0.31300196 -0.57157302  0.1766835 ]
 [-0.32788203  1.0849781  -0.39229512  0.69973449 -1.4552792 ]
 [ 0.76477971 -0.80579564 -0.0286173   0.38161299  0.82247905]
 [-1.55943906  0.23298095  1.34493272 -0.1844541  -1.30630419]
 [ 0.95266473 -0.79504166  0.04220883 -1.3930498  -1.40163327]
 [-1.51565257  1.29587529 -1.18711163 -1.51492776  2.24416861]
 [ 0.04427762  0.44446508  0.14172478  1.3246338   0.42332305]
 [-1.60205273 -0.13787747  0.78387438  0.82458148  0.40024539]
 [-0.08692325 -1.57381375 -0.90913917  0.91433228 -0.61311508]]


In [12]:
# we can also use numpy for statistical tools on arrays
print(np.mean(rand_mat))
print(np.std(rand_mat2))

0.5249737926715892
0.9911873268266991


In [13]:
print(np.min(rand_mat))
print(np.max(rand_mat2))

0.001982995973899393
2.244168611377814


In [14]:
# break here for next video!

In [15]:
# how do we access entries in a numpy vector
rand_vec = np.random.randn(19)
print(rand_vec)
print(rand_vec[6])

[ 0.69088393 -0.91074289 -0.64824126  0.1844039   1.83685178  0.85108208
  1.67779615  0.70758691  0.22568017 -0.99090019  1.09506742  1.19980111
  0.11893625 -0.98796452  0.02521824 -0.88656889 -1.44507517 -1.64822676
  0.48444318]
1.6777961531179222


In [21]:
# we can access multiple entries at once using :
print(rand_vec[-2:-1])

[-1.64822676]


In [22]:
# we can also access multiple non-consecutive entries using np.arange
print(np.arange(0,15,3))
print(rand_vec[np.arange(0,15,3)])

[ 0  3  6  9 12]
[ 0.69088393  0.1844039   1.67779615 -0.99090019  0.11893625]


In [23]:
# what about matrices
print(rand_mat)
print(rand_mat[1][2])
print(rand_mat[1,2])


[[0.80339305 0.3443665  0.11965859 0.33054602 0.82775485]
 [0.80834343 0.91693695 0.60062788 0.82067113 0.74608966]
 [0.2556618  0.8373035  0.30890033 0.59713354 0.42069145]
 [0.86890498 0.28781749 0.49102024 0.38748334 0.40055826]
 [0.62741964 0.001983   0.75107944 0.26270882 0.30729093]]
0.6006278768514439
0.6006278768514439


In [24]:
print(rand_mat[0:2,1:3])

[[0.3443665  0.11965859]
 [0.91693695 0.60062788]]


In [25]:
# let's change some values in an array!
print(rand_vec)
rand_vec[3:5] = 4
print('')
print(rand_vec)
rand_vec[3:5] = [1,2]
print('')
print(rand_vec)

[ 0.69088393 -0.91074289 -0.64824126  0.1844039   1.83685178  0.85108208
  1.67779615  0.70758691  0.22568017 -0.99090019  1.09506742  1.19980111
  0.11893625 -0.98796452  0.02521824 -0.88656889 -1.44507517 -1.64822676
  0.48444318]

[ 0.69088393 -0.91074289 -0.64824126  4.          4.          0.85108208
  1.67779615  0.70758691  0.22568017 -0.99090019  1.09506742  1.19980111
  0.11893625 -0.98796452  0.02521824 -0.88656889 -1.44507517 -1.64822676
  0.48444318]

[ 0.69088393 -0.91074289 -0.64824126  1.          2.          0.85108208
  1.67779615  0.70758691  0.22568017 -0.99090019  1.09506742  1.19980111
  0.11893625 -0.98796452  0.02521824 -0.88656889 -1.44507517 -1.64822676
  0.48444318]


In [26]:
print(rand_mat)
rand_mat[1:3,3:5] = 0
print('')
print(rand_mat)

[[0.80339305 0.3443665  0.11965859 0.33054602 0.82775485]
 [0.80834343 0.91693695 0.60062788 0.82067113 0.74608966]
 [0.2556618  0.8373035  0.30890033 0.59713354 0.42069145]
 [0.86890498 0.28781749 0.49102024 0.38748334 0.40055826]
 [0.62741964 0.001983   0.75107944 0.26270882 0.30729093]]

[[0.80339305 0.3443665  0.11965859 0.33054602 0.82775485]
 [0.80834343 0.91693695 0.60062788 0.         0.        ]
 [0.2556618  0.8373035  0.30890033 0.         0.        ]
 [0.86890498 0.28781749 0.49102024 0.38748334 0.40055826]
 [0.62741964 0.001983   0.75107944 0.26270882 0.30729093]]


In [27]:
sub_mat = rand_mat[0:2,0:3]
print(sub_mat)
sub_mat[:] = 3
print(sub_mat)


[[0.80339305 0.3443665  0.11965859]
 [0.80834343 0.91693695 0.60062788]]
[[3. 3. 3.]
 [3. 3. 3.]]


In [28]:
print(rand_mat)

[[3.00000000e+00 3.00000000e+00 3.00000000e+00 3.30546022e-01
  8.27754853e-01]
 [3.00000000e+00 3.00000000e+00 3.00000000e+00 0.00000000e+00
  0.00000000e+00]
 [2.55661796e-01 8.37303497e-01 3.08900327e-01 0.00000000e+00
  0.00000000e+00]
 [8.68904979e-01 2.87817491e-01 4.91020244e-01 3.87483343e-01
  4.00558262e-01]
 [6.27419642e-01 1.98299597e-03 7.51079437e-01 2.62708819e-01
  3.07290931e-01]]


In [29]:
sub_mat2 = rand_mat[0:2,0:3].copy()
sub_mat2[:] = 99
print(sub_mat2)
print(rand_mat)


[[99. 99. 99.]
 [99. 99. 99.]]
[[3.00000000e+00 3.00000000e+00 3.00000000e+00 3.30546022e-01
  8.27754853e-01]
 [3.00000000e+00 3.00000000e+00 3.00000000e+00 0.00000000e+00
  0.00000000e+00]
 [2.55661796e-01 8.37303497e-01 3.08900327e-01 0.00000000e+00
  0.00000000e+00]
 [8.68904979e-01 2.87817491e-01 4.91020244e-01 3.87483343e-01
  4.00558262e-01]
 [6.27419642e-01 1.98299597e-03 7.51079437e-01 2.62708819e-01
  3.07290931e-01]]


In [30]:
# break here for next video

In [31]:
# we can also access entries with logicals
rand_vec = np.random.randn(15)

print(rand_vec)
print(rand_vec>0)
print(rand_vec[rand_vec>0])

[-0.02580978 -0.65264227  0.3159884   0.12564362  0.3108247   0.02179165
 -0.03539453  1.3715932   1.16580995  0.93177222 -0.79328243 -0.08405325
  0.09915764  1.68621009  0.22454068]
[False False  True  True  True  True False  True  True  True False False
  True  True  True]
[0.3159884  0.12564362 0.3108247  0.02179165 1.3715932  1.16580995
 0.93177222 0.09915764 1.68621009 0.22454068]


In [32]:
print(rand_mat2)
print(rand_mat2[rand_mat2>0])

[[-1.18796881  1.60797976  0.19256138 -1.57018676  0.50343537]
 [-1.0667398   0.56265413 -0.31300196 -0.57157302  0.1766835 ]
 [-0.32788203  1.0849781  -0.39229512  0.69973449 -1.4552792 ]
 [ 0.76477971 -0.80579564 -0.0286173   0.38161299  0.82247905]
 [-1.55943906  0.23298095  1.34493272 -0.1844541  -1.30630419]
 [ 0.95266473 -0.79504166  0.04220883 -1.3930498  -1.40163327]
 [-1.51565257  1.29587529 -1.18711163 -1.51492776  2.24416861]
 [ 0.04427762  0.44446508  0.14172478  1.3246338   0.42332305]
 [-1.60205273 -0.13787747  0.78387438  0.82458148  0.40024539]
 [-0.08692325 -1.57381375 -0.90913917  0.91433228 -0.61311508]]
[1.60797976 0.19256138 0.50343537 0.56265413 0.1766835  1.0849781
 0.69973449 0.76477971 0.38161299 0.82247905 0.23298095 1.34493272
 0.95266473 0.04220883 1.29587529 2.24416861 0.04427762 0.44446508
 0.14172478 1.3246338  0.42332305 0.78387438 0.82458148 0.40024539
 0.91433228]


In [33]:

print(rand_vec)
print('')
rand_vec[rand_vec>0.5] = -5
print(rand_vec)

[-0.02580978 -0.65264227  0.3159884   0.12564362  0.3108247   0.02179165
 -0.03539453  1.3715932   1.16580995  0.93177222 -0.79328243 -0.08405325
  0.09915764  1.68621009  0.22454068]

[-0.02580978 -0.65264227  0.3159884   0.12564362  0.3108247   0.02179165
 -0.03539453 -5.         -5.         -5.         -0.79328243 -0.08405325
  0.09915764 -5.          0.22454068]


In [34]:
# let's save some arrays on the disk for use later!
np.save('saved_file_name',rand_mat2)


In [35]:
np.savez('zipped_file_name',rand_mat=rand_mat,rand_mat2=rand_mat2)

In [36]:
# now let's load it
loaded_vec = np.load('saved_file_name.npy')
loaded_zip = np.load('zipped_file_name.npz')

print(loaded_vec)
print('')
print(loaded_zip)

[[-1.18796881  1.60797976  0.19256138 -1.57018676  0.50343537]
 [-1.0667398   0.56265413 -0.31300196 -0.57157302  0.1766835 ]
 [-0.32788203  1.0849781  -0.39229512  0.69973449 -1.4552792 ]
 [ 0.76477971 -0.80579564 -0.0286173   0.38161299  0.82247905]
 [-1.55943906  0.23298095  1.34493272 -0.1844541  -1.30630419]
 [ 0.95266473 -0.79504166  0.04220883 -1.3930498  -1.40163327]
 [-1.51565257  1.29587529 -1.18711163 -1.51492776  2.24416861]
 [ 0.04427762  0.44446508  0.14172478  1.3246338   0.42332305]
 [-1.60205273 -0.13787747  0.78387438  0.82458148  0.40024539]
 [-0.08692325 -1.57381375 -0.90913917  0.91433228 -0.61311508]]



In [37]:
print(loaded_zip['rand_mat'])
print('')
print(loaded_zip['rand_mat2'])

new_array  = loaded_zip['rand_mat']
print(new_array)

[[3.00000000e+00 3.00000000e+00 3.00000000e+00 3.30546022e-01
  8.27754853e-01]
 [3.00000000e+00 3.00000000e+00 3.00000000e+00 0.00000000e+00
  0.00000000e+00]
 [2.55661796e-01 8.37303497e-01 3.08900327e-01 0.00000000e+00
  0.00000000e+00]
 [8.68904979e-01 2.87817491e-01 4.91020244e-01 3.87483343e-01
  4.00558262e-01]
 [6.27419642e-01 1.98299597e-03 7.51079437e-01 2.62708819e-01
  3.07290931e-01]]

[[-1.18796881  1.60797976  0.19256138 -1.57018676  0.50343537]
 [-1.0667398   0.56265413 -0.31300196 -0.57157302  0.1766835 ]
 [-0.32788203  1.0849781  -0.39229512  0.69973449 -1.4552792 ]
 [ 0.76477971 -0.80579564 -0.0286173   0.38161299  0.82247905]
 [-1.55943906  0.23298095  1.34493272 -0.1844541  -1.30630419]
 [ 0.95266473 -0.79504166  0.04220883 -1.3930498  -1.40163327]
 [-1.51565257  1.29587529 -1.18711163 -1.51492776  2.24416861]
 [ 0.04427762  0.44446508  0.14172478  1.3246338   0.42332305]
 [-1.60205273 -0.13787747  0.78387438  0.82458148  0.40024539]
 [-0.08692325 -1.57381375 -0.90

In [ ]:
# we can also save/load as text files...but only single variables
np.savetxt('text_file_name.txt',rand_mat,delimiter=',')
rand_mat_txt = np.loadtxt('text_file_name.txt',delimiter=',')
print(rand_mat)
print('')
print(rand_mat_txt)